Traceback (most recent call last):
  File "/home/javier.ares/citius/mamba.py", line 208, in <module>
    y = model(x_train)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/mamba_ssm/modules/mamba_simple.py", line 169, in forward
    x = self.act(self.conv1d(x)[..., :seqlen])
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/javier.ares/miniconda3/envs/suffixprediction/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected canUse32BitIndexMath(input) && canUse32BitIndexMath(output) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
